# Generated by Django 3.1 on 2022-02-13 08:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime(2022, 2, 13, 8, 27, 41, 230676, tzinfo=utc))),
                ('chest', models.PositiveIntegerField()),
                ('left_arm', models.PositiveIntegerField()),
                ('right_arm', models.PositiveIntegerField()),
                ('body_weight', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime(2022, 2, 13, 8, 27, 41, 215275, tzinfo=utc))),
                ('type', models.CharField(choices=[('benchPress', 'ベンチプレス'), ('dumbbellPress', 'ダンベルプレス'), ('decline_benchPress', 'デクラインベンチプレス'), ('dumbbellFly', 'ダンベルフライ'), ('chinning', 'チンニング')], max_length=30)),
                ('phase', models.CharField(choices=[('normal', '基本'), ('highWeight', '高重量'), ('lowWeight', '低重量')], default='normal', max_length=30)),
                ('weight', models.PositiveIntegerField()),
                ('rep', models.PositiveIntegerField()),
            ],
        ),
    ]
