# Generated by Django 3.1 on 2022-02-14 02:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='day',
            field=models.DateField(default=datetime.datetime(2022, 2, 14, 2, 33, 35, 56959, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='training',
            name='day',
            field=models.DateField(default=datetime.datetime(2022, 2, 14, 2, 33, 35, 41860, tzinfo=utc)),
        ),
    ]
