# Generated by Django 3.1 on 2022-02-15 01:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220214_1135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.AlterField(
            model_name='training',
            name='day',
            field=models.DateField(default=datetime.datetime(2022, 2, 15, 1, 34, 35, 744227, tzinfo=utc)),
        ),
    ]
