# Generated by Django 3.1 on 2022-02-15 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220215_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='day',
            field=models.DateField(default=datetime.datetime(2022, 2, 15, 13, 48, 26, 634992, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='training',
            name='type',
            field=models.CharField(choices=[('benchPress', 'ベンチプレス'), ('dumbbellPress', 'ダンベルプレス'), ('decline_benchPress', 'デクラインベンチプレス'), ('dumbbellFly', 'ダンベルフライ'), ('dumbbellRow', 'ダンベルロウ'), ('chinning', 'チンニング')], max_length=30),
        ),
    ]
