# Generated by Django 3.1 on 2022-02-11 10:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220211_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.DateField(default=datetime.datetime(2022, 2, 11, 10, 6, 50, 932965, tzinfo=utc)),
        ),
    ]
