# Generated by Django 3.1 on 2022-02-11 10:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayEtc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_etc', models.DateField(default=datetime.datetime(2022, 2, 11, 10, 1, 36, 559090, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(max_length=100)),
                ('day_etc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etc.dayetc')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100)),
                ('length', models.PositiveIntegerField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('done', models.BooleanField(default=False)),
                ('day_etc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etc.dayetc')),
            ],
        ),
    ]
