# Generated by Django 3.1 on 2022-02-13 08:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0006_auto_20220213_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayetc',
            name='day_etc',
            field=models.DateField(default=datetime.datetime(2022, 2, 13, 8, 18, 56, 135553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 2, 13, 8, 18, 56, 135753, tzinfo=utc)),
        ),
    ]
