# Generated by Django 3.1 on 2022-02-13 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0007_auto_20220213_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayetc',
            name='day_etc',
            field=models.DateField(default=datetime.datetime(2022, 2, 13, 8, 25, 41, 827106, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 2, 13, 8, 25, 41, 827317, tzinfo=utc)),
        ),
    ]
