# Generated by Django 3.1 on 2022-02-14 02:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0009_auto_20220213_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='day_etc',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='day_etc',
        ),
        migrations.AddField(
            model_name='goal',
            name='day',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='day',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 2, 14, 2, 33, 35, 58574, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='DayEtc',
        ),
    ]
