# Generated by Django 3.1 on 2022-02-14 02:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0010_auto_20220214_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 2, 14, 2, 35, 31, 200646, tzinfo=utc)),
        ),
    ]
