# Generated by Django 3.1 on 2022-02-15 01:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0011_auto_20220214_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime(2022, 2, 15, 1, 34, 35, 760927, tzinfo=utc))),
                ('chest', models.PositiveIntegerField()),
                ('left_arm', models.PositiveIntegerField()),
                ('right_arm', models.PositiveIntegerField()),
                ('body_weight', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 2, 15, 1, 34, 35, 760568, tzinfo=utc)),
        ),
    ]
