# Generated by Django 3.1 on 2022-02-15 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0012_auto_20220215_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 2, 15, 13, 48, 26, 666863, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='day',
            field=models.DateField(default=datetime.datetime(2022, 2, 15, 13, 48, 26, 667369, tzinfo=utc)),
        ),
    ]
